### ISSUE TITLE
User Guide - label 4.7 as "Latest" and 4.6 as "LTS"

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-docs#51]
This is in response to a request from @nganivet [here](https://github.com/civicrm/civicrm-docs/pull/49#issuecomment-286637921). Specific changes to implement:

* [x] Update [civicrm.org/documentation](https://civicrm.org/documentation) to change the URL for User Guide 4.7 from `/user/en/stable` to `/user/en/latest` **(Done by Sean on 2017-03-15)**
* [ ] Redirect `user/en/stable` to `/user/en/latest` **(Blocked by #50)** *(Note: this change is just to avoid giving 404s to any "stable" URLs which still exist in the wild, since people have been using this URL for the 4.7 version of the User Guide for quite some time now. The term "stable" would not be displayed to any readers anywhere, but would just function as a redirect)*
* [ ] Redirect `/user/en/lts` to `/user/en/4.6` **(Blocked by #50)**
* [ ] When describing the available editions of the User Guide to readers, do it as follows: **(Blocked by #50 and #48 and #46 )** *(Note: these descriptors will eventually be used in the auto-generated book home pages, as well as at the top of every page within the book when the book is built with the Material theme customizations)*
    * "English &ndash; 4.7 (Latest)"
    * "English &ndash; 4.6 (LTS)"
    * "françias (French) &ndash; 4.7 (Latest)"
